### ISSUE TITLE
[Feature Request] Please provide a way to backup the Mnemonic with the web wallet

### ISSUE THREAD

**Issue by berndfue** [kardiachain/go-kardia#132]
Hi!

Please provide a way to backup the Mnemonic with the web wallet.
This is usually a feature of other web wallets but can't be found in yours.
If you have created the wallet with a keystore file you can never switch to the e.g. mobile wallet because you don't have the mnemonic.
Thanks!

Cheers,
BF

**Comment by lewtran** [comment]
Close due to this proposal should be in KardiaChain Explorer repo. Thank you for your suggestion, we will consider implement this feature
