### ISSUE TITLE
Are there any public nodes for rpc testing?

### ISSUE THREAD

**Issue by leeheejoo** [kardiachain/go-kardia#141]
Are there any public nodes for rpc testing?

**Comment by lewtran** [comment]
> Are there any public nodes for rpc testing?

Please refer to https://rpc.kardiachain.io

**Comment by leeheejoo** [comment]
Thank you. That's great.

**Comment by lewtran** [comment]
> Thank you. That's great.

You can also check our RPC Documents at
https://github.com/kardiachain/go-kardia/wiki/Kardia-JSON-RPC-API

**Comment by lewtran** [comment]
Close due to resolved
